name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # every day at midnight
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent, calendar 
          plugin_leetcode_user: A56A5
